 <h1><?=$this->escape($this->title);?></h1>
 <br />
 <form method='post' action='<?=$this->escape($this->action);?>'>
    <table border="0" width="368" align="center" cellspacing="3" cellpadding="6">
        <tr>
            <td><?=$this->escape($this->username);?></td>
            <td><input type='text' name='username' id="username" class="inputs"></td>
        </tr>

        <tr>
            <td><?=$this->escape($this->password);?></td>
            <td><input type='password' name='password' id="password" class="inputs"></td>
        </tr>

        <tr>
            <th colspan="2">
                <div class="error">
                    <?=$this->escape($this->error);?>
                </div>
            </th>
        </tr>

        <tr>
            
            <td colspan="2">
                <input type='submit' name='login' value='Prisijungti' id="sub_button" class="btn"
                       onmouseover="this.className='btn btnhov'" onmouseout="this.className='btn'">
            </td>
            
        </tr>
        <tr>
            <td colspan="2">
                 <a href='register'>Registruotis</a>
            </td>
        </tr>
    </table>
 </form>
 
 <br />




