<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
        <title><?php echo $this->escape($this->title); ?></title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/main.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/general.css"/>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/sub_menu.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.js"></script>
    </head>
    <body>
        <center>
        <div id="main">
            
           <div id="content">
                <?php
                    echo $this->layout()->content;
                ?>
          </div> <!-- content-->

            <div id="left">
                
                <div class="menu_logo">
                    LOGO?
                </div>

                <div class="menu">
                    <?php
                       echo $this->navigation();
                    ?>
                </div><!-- menu-->

                
            </div> <!--left-->

            <div class=”clearer”></div> 
           
        </div> <!-- main-->
             <div id="footer"></div>
             
        </center>
    </body>
</html>

